# fly.toml app configuration for the jimumember blueprint
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remember-staging'
primary_region = 'syd'

[build]

[env]
  HOST = "0.0.0.0"

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines = 1
  processes = ['app']

[[http_service.checks]]
  interval = "5m"
  timeout = "15s"
  grace_period = "1m"
  method = "GET"
  path = "/api/health"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
